class MenuMakanan {
  final int id;
  final List<String>? image;
  final String namaMakanan, lokasi, bahan, alat, caraMasak, review;
  final double rateReview;

  MenuMakanan({
    required this.id,
    required this.namaMakanan,
    required this.image,
    required this.lokasi,
    required this.bahan,
    required this.alat,
    required this.caraMasak,
    required this.review,
    required this.rateReview,
  });
}

List<MenuMakanan> menuMakananList = [
  MenuMakanan(
    id: 1,
    namaMakanan: 'Nasi Liwet Cianjur',
    image: ['assets/images/liwet.png'],  
    lokasi: 'Saung Liwet Mirah',
    bahan: 'Nasi, ayam, ikan asin, sambel, daun salam, santan.',
    alat: 'Rice cooker, panci, sendok, mangkok.',
    caraMasak: 'Pertama, cuci beras dan masak nasi dengan santan dalam rice cooker hingga matang. Sambil menunggu nasi matang, siapkan ayam yang sudah dibumbui dengan rempah seperti bawang putih, kunyit, jahe, dan merica. Goreng ayam hingga kecoklatan dan matang. Setelah itu, siapkan ikan asin yang telah digoreng. Sajikan nasi liwet dengan ayam goreng, ikan asin, sambel, dan daun salam sebagai pelengkap.',
    review: 'Nasi liwet yang gurih dan wangi, dengan rasa yang mendalam berkat santan yang meresap ke dalam nasi. Kombinasi ayam goreng yang empuk dan ikan asin yang renyah memberikan cita rasa yang khas dan lezat.',
    rateReview: 4.8,
  ),
  MenuMakanan(
    id: 2,
    namaMakanan: 'Laksa Cianjur',
    image: ['assets/images/laksa.png'],  
    lokasi: 'Laksa Kang Aam',
    bahan: 'Mie kuning, santan, oncom, tauge, daun bawang, seledri.',
    alat: 'Panci, sendok, mangkok.',
    caraMasak: 'Pertama, masak santan dengan bumbu seperti bawang merah, bawang putih, dan rempah lainnya hingga harum dan mendidih. Setelah itu, tambahkan mie kuning ke dalam santan dan masak hingga mie matang. Sajikan mie dalam mangkok, lalu tambahkan oncom yang sudah dipanaskan, tauge, daun bawang, dan seledri sebagai topping. Laksa siap dinikmati dengan kuah santan yang gurih dan rasa khas dari oncom.',
    review: 'Laksa ini memiliki rasa yang sangat gurih dan kaya akan rempah. Kombinasi mie kuning yang kenyal dengan kuah santan yang kental membuat hidangan ini sangat memanjakan lidah. Oncom yang khas memberikan sentuhan rasa yang berbeda dari laksa pada umumnya.',
    rateReview: 4.5,
  ),
  MenuMakanan(
    id: 3,
    namaMakanan: 'Geco Cianjur',
    image: ['assets/images/geco.png'],  
    lokasi: 'Geco Cap Meong',
    bahan: 'Tauge, tauco, mie kuning, tahu, bumbu kacang.',
    alat: 'Panci, sendok, piring.',
    caraMasak: 'Rebus tauge dan mie kuning hingga matang. Sementara itu, haluskan bumbu kacang yang terdiri dari kacang tanah, cabai, bawang putih, dan gula merah. Setelah tauge dan mie matang, campurkan dengan tauco dan bumbu kacang yang sudah dihaluskan. Tambahkan tahu goreng potong kecil dan sajikan di atas piring.',
    review: 'Geco, atau toge tauco, merupakan hidangan sederhana namun kaya rasa. Rasanya gurih, pedas, dan sedikit manis dari bumbu kacang yang membuatnya sangat enak. Hidangan ini sangat cocok sebagai teman makan siang yang menyegarkan.',
    rateReview: 4.6,
  ),
  MenuMakanan(
    id: 4,
    namaMakanan: 'Sate Maranggi Cianjur',
    image: ['assets/images/sate.png'],  
    lokasi: 'Sate Maranggi Sari Asih',
    bahan: 'Daging sapi, kecap, bawang putih, jahe, merica.',
    alat: 'Tusuk sate, panggangan.',
    caraMasak: 'Pertama, potong daging sapi menjadi potongan kecil dan rendam dengan bumbu yang terdiri dari kecap, bawang putih, jahe, dan merica selama beberapa jam agar bumbu meresap. Setelah itu, tusuk daging yang telah dibumbui pada tusuk sate. Panggang sate di atas bara api hingga matang dan sedikit kecoklatan. Sajikan sate maranggi dengan sambel kecap atau sambel oncom.',
    review: 'Sate maranggi memiliki rasa yang luar biasa dengan daging yang empuk dan bumbu yang meresap hingga ke dalam. Kecap manis yang digunakan memberikan rasa manis yang khas, membuat setiap gigitan semakin nikmat.',
    rateReview: 4.8,
  ),
  MenuMakanan(
    id: 5,
    namaMakanan: 'Ayam Puyang Cianjur',
    image: ['assets/images/puyang.png'],  
    lokasi: 'Nasi Balap Baiq',
    bahan: 'Ayam, santan, kunyit, daun jeruk.',
    alat: 'Wajan, kompor.',
    caraMasak: 'Pertama, lumuri ayam dengan bumbu halus yang terdiri dari kunyit, bawang putih, dan jahe. Masukkan ayam ke dalam wajan, lalu tambahkan santan dan daun jeruk. Masak dengan api kecil hingga ayam matang dan bumbu meresap. Sajikan ayam dengan kuah santan yang kental dan harum.',
    review: 'Ayam puyang memiliki rasa yang gurih dan kaya akan rempah. Kuah santan yang kental memberikan kelembutan pada ayam, sementara aroma kunyit dan daun jeruk menambah kenikmatan rasa.',
    rateReview: 4.5,
  ),
  MenuMakanan(
    id: 6,
    namaMakanan: 'Karedok Cianjur',
    image: ['assets/images/karedok.png'], 
    lokasi: 'Lotek Ceu Piah',
    bahan: 'Sayuran segar (timun, tauge, kacang panjang), bumbu kacang, tahu, tempe.',
    alat: 'Panci, sendok, piring.',
    caraMasak: 'Campurkan sayuran segar seperti timun, tauge, dan kacang panjang dalam satu wadah. Haluskan bumbu kacang dengan cabai, bawang putih, dan gula merah hingga halus dan menyatu. Tambahkan bumbu kacang ke dalam sayuran dan campurkan dengan tahu dan tempe goreng yang telah dipotong-potong. Sajikan segera.',
    review: 'Karedok segar dengan rasa pedas, manis, dan gurih dari bumbu kacang yang menyelimuti sayuran. Hidangan ini cocok sebagai salad yang mengenyangkan dan menyegarkan.',
    rateReview: 4.6,
  ),
  MenuMakanan(
    id: 7,
    namaMakanan: 'Soto Cianjur',
    image: ['assets/images/soto.png'], 
    lokasi: 'Kedai Soto Nenek',
    bahan: 'Daging sapi, kentang, tomat, daun bawang, seledri, bihun.',
    alat: 'Panci, sendok, mangkok.',
    caraMasak: 'Rebus daging sapi dengan bumbu hingga empuk. Setelah itu, tambahkan kentang, bihun, dan sayuran seperti tomat, daun bawang, dan seledri. Masak hingga semua bahan matang dan sajikan dalam mangkok dengan kuah bening yang segar.',
    review: 'Soto Cianjur ini memiliki kuah yang bening namun kaya rasa. Daging sapi yang empuk berpadu sempurna dengan sayuran segar dan bihun yang kenyal.',
    rateReview: 4.6,
  ),
  MenuMakanan(
    id: 8,
    namaMakanan: 'Pepes Ikan Cianjur',
    image: ['assets/images/pepes.png'],  
    lokasi: 'Rumah Makan H.NANA',
    bahan: 'Ikan, daun pisang, bumbu rempah, kemangi, tomat.',
    alat: 'Daun pisang, kukusan, wajan.',
    caraMasak: 'Bumbui ikan dengan rempah seperti bawang merah, bawang putih, kunyit, jahe, dan cabai. Bungkus ikan dengan daun pisang dan kukus hingga matang. Sajikan dengan daun kemangi dan potongan tomat.',
    review: 'Pepes ikan ini memiliki rasa yang gurih dan penuh rempah. Daun pisang memberikan aroma yang khas dan menambah kelezatan ikan yang dimasak dengan cara kukus.',
    rateReview: 4.7,
  ),
  MenuMakanan(
    id: 9,
    namaMakanan: 'Bubur Ayam Cianjur',
    image: ['assets/images/bubur.png'],  
    lokasi: 'Bubur Santiong',
    bahan: 'Beras, ayam, bawang goreng, seledri.',
    alat: 'Panci, sendok, mangkok.',
    caraMasak: 'Rebus beras hingga menjadi bubur, kemudian tambahkan topping ayam suwir, bawang goreng, dan seledri. Sajikan dalam mangkok dengan kuah kaldu ayam yang gurih.',
    review: 'Bubur ayam ini sangat lembut dan memiliki rasa yang gurih. Topping ayam dan bawang goreng memberikan sensasi rasa yang enak di setiap suapan.',
    rateReview: 4.7,
  ),
  MenuMakanan(
    id: 10,
    namaMakanan: 'Colenak Cianjur',
    image: ['assets/images/colenak.png'], 
    lokasi: 'Colenak Legit',
    bahan: 'Peuyeum, gula merah, kelapa parut.',
    alat: 'Wajan, sendok.',
    caraMasak: 'Panggang peuyeum hingga sedikit garing, kemudian siram dengan gula merah cair dan taburi kelapa parut di atasnya. Sajikan hangat.',
    review: 'Colenak merupakan makanan penutup yang manis dan gurih, dengan rasa peuyeum yang khas dan gula merah yang melimpah.',
    rateReview: 4.8,
  ),
];
